Homepage nav bar
Elim-J/Capstone-Project pull request #17
Opened 2022-11-10 14:20 UTC by Elim-J

2022-11-10 17:53 UTC, WajahatAliShah1 submitted a review, later dismissed
Updated the homepage-navbar branch with the main branch and it looks good to replace main

2022-11-10 18:10 UTC, WajahatAliShah1 requested changes
Fix Footer issues on pages, get better styling on algo landing page, populate router links to the proper urls for visualizers

2022-11-13 23:22 UTC, WajahatAliShah1 approved these changes

2022-11-14 00:37 UTC, houghta4 approved these changes

2022-11-14 00:37 UTC, merged